# Generated by Django 4.0.5 on 2022-07-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveBigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
